spring:
  data:
    elasticsearch:
      properties:
        path:
          logs: ./elasticsearch/log
          data: ./elasticsearch/data
  mail:
    host: smtp.exmail.qq.com
    username: 1732768613@qq.com
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true